### ISSUE TITLE
Memory leak in exchange calls

### ISSUE THREAD

**Issue by southbite** [happner/happner#76] opened 2016-03-30 11:51 UTC
according to Johan, this is a leak - have tested to ensure it is not actually stored on disk

**Comment by JohanvdWest** [comment] 2016-03-31 09:19
The previous issue was the LRU cache growing until it hits the 1000 entries.

We have now identified a leak where the closure that calls an exchange call lives forever.

**Comment by JohanvdWest** [comment] 2016-03-31 19:11
The issue is in happn, not happner. Closing.

**Closed** 2016-03-31 19:11 UTC
Labels: High Priority
