### ISSUE TITLE
FATAL: Redefine property:post

### ISSUE THREAD

**Issue by cordellcalitz** [happner/happner#70] opened 2016-01-25 08:59 UTC
When using the meshClient (in browser or PC) we sometimes seeing this error:

[FATAL] - 7147ms        bristlethumb_4kEDD2hul (Mesh) uncaughtException (or set NO_EXIT_ON_UNCAUGHT) [TypeError: Cannot redefine property: post]
[FATAL] - TypeError: Cannot redefine property: post
    at Function.defineProperty (native)
    at Object.Internals._initializeLocal (/node_js/node_modules/happner/lib/system/shared/internals.js:25:12)
    at Object.handler (/node_js/node_modules/happner/lib/system/shared/mesh-client.js:293:21)
    at Object.<anonymous> (/node_js/node_modules/happn/lib/client/base.js:359:16)
    at HappnClient.handle_response_array (/node_js/node_modules/happn/lib/client/base.js:526:19)
    at HappnClient.handle_publication (/node_js/node_modules/happn/lib/client/base.js:486:11)
    at Primus.emit (events.js:98:17)
    at done (primus.js:2243:48)
    at transform (primus.js:2214:30)
    at Primus.transforms (primus.js:2235:4)
    at decoding (primus.js:2012:14)
    at Primus.decoder (primus.js:2817:3)
    at Primus.message (primus.js:2001:12)
    at Primus.emit (events.js:95:17)
    at next (primus.js:140:17)
    at defer [as _onTimeout] (primus.js:2766:9)

**Comment by JensEggers** [comment] 2016-04-04 10:39
apparently fixed in 1.6.7 but never closed

**Comment by JensEggers** [comment] 2016-04-04 10:45
closing in favour of https://github.com/happner/happn/issues/25

**Comment by JensEggers** [comment] 2016-04-04 10:55
Some clues:
- this only ever seems to happen when client or server is a Brain
- could point at a timing issue in reconnect logic (maybe use timeout, not interval)

**Comment by nomilous** [comment] 2016-04-04 10:56
Taking this on.

**Comment by nomilous** [comment] 2016-04-04 10:59
This sounds like one of those we can only "think" we fixed until it happens again.

**Comment by nomilous** [comment] 2016-04-04 11:47
This pertains to the mesh startup issue where the server's datalayer is listening and allows connections (very first step in mesh server) but is not yet ready to provide the schema to the connecting client.

So the connection is a three step activity.

1. Make the datalayer connection.
2. Enter into loop attempting to get `/mesh/schema/description`
3. Use the `description` to assemble local api exchange

Step 2 is __overlapping__ leading to multiple step 3s, because the `busy` flag as set is never used as intended (to prevent the __overlap__).

Fixed

https://github.com/happner/happner/commit/cc37eff16e7afb258b4ae4a91550f6c5f29e9f40

Not yet merged into master.

**Comment by JensEggers** [comment] 2016-04-04 12:03
Let's keep this open until a fix is in master. Pls see suggested work flow on Slack.

**Comment by nomilous** [comment] 2016-04-04 12:18
fixes issues/70-overlapping-reconnect

**Comment by nomilous** [comment] 2016-04-04 12:20
fixes #issues/70-overlapping-reconnect

**Comment by nomilous** [comment] 2016-04-04 12:21
fixes issue/70-overlapping-reconnect

**Comment by nomilous** [comment] 2016-04-04 12:22
fixes issue/#70-overlapping-reconnect

**Comment by nomilous** [comment] 2016-04-04 12:55
fixes #79

**Comment by nomilous** [comment] 2016-04-04 13:46
closes #79

**Closed** 2016-04-04 13:47 UTC
Labels: bug, High Priority
